version: '2'

# settings and configurations that are common for all minio containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2023-04-20T17-56-55Z
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: ${MINIO_ROOT_USER}
    MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

# starts postgres, redis and
# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  db:
    image: postgres:13.1-alpine
    container_name: rust-sveltekit-auth-starter-db
    restart: unless-stopped
    ports:
      - 5434:5432
    volumes:
      - ./volumes/postgres/var/lib/postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  redis:
    image: redis:latest
    container_name: rust-sveltekit-auth-starter-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis/root/redis:/root/redis
      - ./volumes/redis/usr/local/etc/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      # REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

#  surrealdb:
#    image: surrealdb/surrealdb:latest
#    container_name: rust-sveltekit-auth-starter-surrealdb
#    restart: always
#    command: start --user ${SURREALDB_USERNAME} --pass ${SURREALDB_PASSWORD} file:/data/database.db
#    ports:
#      - 8000:8000
#    volumes:
#      - ./volumes/surrealdb/data:/data

  minio1:
    <<: *minio-common
    hostname: minio1
    container_name: rust-sveltekit-auth-starter-minio1
    volumes:
      - ./volumes/minio/data1-1:/data1
      - ./volumes/minio/data1-2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2
    container_name: rust-sveltekit-auth-starter-minio2
    volumes:
      - ./volumes/minio/data2-1:/data1
      - ./volumes/minio/data2-2:/data2

  minio3:
    <<: *minio-common
    hostname: minio3
    container_name: rust-sveltekit-auth-starter-minio3
    volumes:
      - ./volumes/minio/data3-1:/data1
      - ./volumes/minio/data3-2:/data2

  minio4:
    <<: *minio-common
    hostname: minio4
    container_name: rust-sveltekit-auth-starter-minio4
    volumes:
      - ./volumes/minio/data4-1:/data1
      - ./volumes/minio/data4-2:/data2

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    container_name: rust-sveltekit-auth-starter-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # this will have broken links inside container pointed to
      # /etc/letsencrypt/live/koakh.com/fullchain.pem -> ../../archive/koakh.com/fullchain7.pem
      # - /etc/letsencrypt/live/koakh.com:/etc/letsencrypt/live/koakh.com
      - ./certs/fullchain.pem:/etc/letsencrypt/live/koakh.com/fullchain.pem
      - ./certs/privkey.pem:/etc/letsencrypt/live/koakh.com/privkey.pem
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4

  # mailhog:
  #   image: mailhog/mailhog:latest
  #   container_name: rust-sveltekit-auth-starter-mailhog
  #   restart: unless-stopped
  #   ports:
  #     - 1025:1025
  #     - 8025:8025
